# see https://github.com/marketplace/actions/release-drafter
# For RESOLVED_VERSION
version-template: '$MAJOR.$MINOR.$PATCH'
#
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
#
template: |
  ### DevSuite $RESOLVED_VERSION
  [Release Notes](https://github.com/kapresoft/$REPOSITORY/releases/tag/$RESOLVED_VERSION) | [Full Changelog](https://github.com/kapresoft/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION) | [Curse Forge](https://www.curseforge.com/wow/addons/devsuite/files)
  <br><br>
  
  #### What’s Changed
  $CHANGES
  <br><br>
    
