--[[

    Please do NOT edit this file.
    The contents of this file will be generated automatically.
    
]]--
local addon = ...
local L = LibStub('AceLocale-3.0'):NewLocale(addon, 'enUS', true);

L['BINDING_NAME_DEVS_OPTIONS_DLG']                     = 'Options Dialog'
L['BINDING_NAME_DEVS_DEBUG_DLG']                       = 'Debug Dialog'
L['BINDING_NAME_DEVS_GET_DETAILS_ON_MOUSEOVER']        = 'Get Details On Mouse Over'

L['Debugging::Category::Enable All::Button']           = 'Enable All'
L['Debugging::Category::Enable All::Button::Desc']     = 'Enables all log categories below. Note that the default category (not shown here) will always be active.'
L['Debugging::Category::Disable All::Button']          = 'Disable All'
L['Debugging::Category::Disable All::Button::Desc']    = 'Disables all log categories below. Note that the default category (not shown here) will always be active.'
L['Addon Usage: Automatically Show UI (Global)']       = true
L['Addon Usage: Automatically Show UI (Global)::Desc'] = 'If enabled, this will automatically show the [Addon Usage] UI after player login. (Global Setting)'

L['REQUIRES_RELOAD']          = 'Additional addons require a reload to take effect. Would you like to reload now?\n\n'
L['General']                  = true
L['General::Desc']            = "General Settings"
L['Add-On Management']        = true
L['Add-On Management::Desc']  = 'Easily enable or disable and customize some of your WoW add-ons for a tailored gameplay experience.'

L['Show Frames-Per-Second (FPS)']               = true
L['Show Frames-Per-Second (FPS)::Desc']         = 'Shows the Blizzard Frames-per-second display (Global Setting)'
L['Prompt to Reload and Enable Addons']         = true
L['Prompt to Reload and Enable Addons::Desc']   = 'Prompts player to Reload UI if addons need to be enabled after closing the Settings Dialog. (Global Setting)'

L['Add-On Specific Options']  = true
L['Available Add-Ons']        = true
L['Available Add-Ons::Desc']  = 'To activate or deactivate an Add-On, check or uncheck its corresponding box. After making your selections, click on "Apply and ReloadUI" to implement the changes to your configuration.'
L['Debugging']                = true
L['Debugging::Desc']          = 'Debug Settings for troubleshooting'
L['Debugging Configuration']  = true

L['Log Level']                = true
L['Log Level::Desc']          = 'Higher log levels generate more logs:\nLog Levels: ERROR(5), WARN(10), INFO(15), DEBUG(20), FINE(25), FINER(30), FINEST(35), TRACE(50)'
L['Apply and ReloadUI']       = true
L['Apply and ReloadUI::Desc'] = 'To activate or deactivate an Add-On, check or uncheck its corresponding box. After making your selections, click on this button to implement the changes to your configuration.'
L['Select Profile']           = true
L['Select Profile::Desc']     = 'Select a profile to activate.  You will be prompted to reload the UI.  Note that these profiles are managed on the Profiles tab.'

