--[[

    Please do NOT edit this file.
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("DevSuite", "enUS", true);

L["BINDING_NAME_DEVS_OPTIONS_DLG"]                  = 'Options Dialog'
L["BINDING_NAME_DEVS_DEBUG_DLG"]                    = 'Debug Dialog'
L["BINDING_NAME_DEVS_GET_DETAILS_ON_MOUSEOVER"]     = 'Get Details On Mouse Over'
