--[[

    Please do NOT edit this file.
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("DevTools", "enUS", true);

L["BINDING_NAME_DEVT_OPTIONS_DLG"]  = 'Options Dialog'
L["BINDING_NAME_DEVT_DEBUG_DLG"]  = 'Debug Dialog'
